### ISSUE TITLE
Highway = track?

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/osmactive#31]
Discussing this with @joeytalbot now and looking at results from Overpass here: https://overpass-turbo.eu/?template=key-value&key=highway&value=track

**Comment by Robinlovelace** [comment]
In fact: Joey's right. There are no examples we can find where highway=track and where there is also good cycle infrastructure. This is fixed in #28.

Sound right to you @mvl22 ? Cheers!

**Comment by Robinlovelace** [comment]
Details: https://overpass-turbo.eu/?template=key-value&key=highway&value=track

There you will see 0 good infra for cycling I think.

![image](https://github.com/nptscot/osmactive/assets/1825120/5a929cba-d225-42f8-aeda-6ee6fcf5d5d3)

**Comment by mvl22** [comment]
`highway=track` is a bit of a junky tag that shouldn't really be used for cycle infrastructure. Not quite as bad as `highway=path` though (though mappers in Germany love that tag).

**Comment by Robinlovelace** [comment]
Yep. Purged. At a future OSM workshop we can talk about this, setting a high bar for correct classification of cycle infra here can help get the tagging in shape, in line with excluding all highway=tracks.

@joeytalbot do we have any paths as highway=path?
