### ISSUE TITLE
fix connectivity issue in OSM

### ISSUE THREAD

**Issue by wangzhao0217** [nptscot/osmactive#49]

**Comment by Robinlovelace** [comment]
:+1: to the issue @wangzhao0217. It would help if you can provide a minimal reporducible example that generates data with a connectivity issue, starting with

```
remotes::install_github("nptscot/osmactive")
```

or similar...

**Comment by wangzhao0217** [comment]
Not a issue with osmactive, so closing

**Comment by Robinlovelace** [comment]
👍
