### ISSUE TITLE
Classification of London's cycle superhighway

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/osmactive#50]
As discussed here, it should not be Along Road infrastructure: https://github.com/nptscot/nptscot.github.io/issues/243#issuecomment-2394703806

**Comment by Robinlovelace** [comment]
It is indeed currently classified as roadside: 

![image](https://github.com/user-attachments/assets/4289d406-29c4-4088-bcde-7520c1588705)

**Comment by Robinlovelace** [comment]
After the changes in #51, which sets a higher bar for the definition of a major road (speed limit is 40 or more, as it is on the Leeds-Bradford cycle superhighway), the classification is different for London:

![image](https://github.com/user-attachments/assets/42f95ec1-5daf-422e-92f6-6ea3746e8d20)

That raises the question, should the 2nd category label be changed, e.g. to "Infrastructure along major road"?

**Comment by mvl22** [comment]
I think this is a clear example of why we should use the six categories in the guidance rather than arbitrarily collapse three very different ones into one. This is one of very many examples now around London and beyond.

**Comment by mvl22** [comment]
> After the changes in #51, which sets a higher bar for the definition of a major road (speed limit is 40 or more, as it is on the Leeds-Bradford cycle superhighway), the classification is different for London

I don't think using the speed limit as the determinant factor is correct. The cycleway is completely separate from the road. So it really makes no difference what the speed limit is - you could set it to 20 or 70 and the safety of the cyclist would be almost exactly the same.

**Comment by Robinlovelace** [comment]
happy to revisit this, suggestions welcome.
