### ISSUE TITLE
Implement a WebTag classification type

### ISSUE THREAD

**Issue by Hussein-Mahfouz** [nptscot/osmactive#53]
In our model of cycle uptake in https://github.com/nptscot/uptake, we will use the guidance in 2.3 Approach 2: Estimating from Disaggregate Mode Choice Models of [TAG UNIT A5.1](https://www.gov.uk/government/publications/tag-unit-a5-1-active-mode-appraisal). The guidance has utilities for (changes in) the following categories of cycling infrastructure:

- `off-road cycle track `
- `segregated on-road cycle lane`
- `non-segregated on-road cycle lane`
- `no facilities`

It would be useful to extend functionality of [classify_cycle_infrastructure](https://github.com/nptscot/osmactive/blob/528dde1d6bef9b6847f7ccab5bf400d278d3d89b/R/osmactive.R#L195) by adding a `classify_cycle_infrastructure_webtag()` option. 

Initial discussion in https://github.com/nptscot/uptake/issues/12

**Comment by Robinlovelace** [comment]
Happy to give this a go but likewise happy for you to if you get there first.
