### ISSUE TITLE
Speed-up distance_to_road

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/osmactive#54]
It's slow: https://github.com/nptscot/uptake/issues/12

**Comment by Robinlovelace** [comment]
https://github.com/nptscot/osmactive/blob/a0c9130a39af9cad642fae27756b628ff633b1de/R/osmactive.R#L154

**Comment by Robinlovelace** [comment]
https://github.com/nptscot/osmactive/blob/a0c9130a39af9cad642fae27756b628ff633b1de/R/osmactive.R#L154-L166

**Comment by Hussein-Mahfouz** [comment]
It's much faster when you don't union the road geometry. Just use `st_nearest_feature` to get the index of the closest road segment to each segregated point, and then `st_distance` to calculate the corresponding distance. I think it's faster because unioning stops you from using spatial a spatial index

I can make a PR. Benchmarking on the osm_edinburgh dataset shows the original function to be quicker, but this function seems much quicker on larger datasets

Function:
```r
distance_to_road_new = function(rnet, roads) {
  # Ensure both 'rnet' and 'roads' are in the same CRS
  rnet = sf::st_transform(rnet, 27700)
  roads = sf::st_transform(roads, 27700)
  # Create the representative points on the road network
  suppressWarnings({
    segregated_points = sf::st_point_on_surface(rnet)
  })
  # Find the nearest road for each point 
  nearest_roads_indices = sf::st_nearest_feature(segregated_points, roads)
  # Extract only the nearest road segments from 'roads'
  nearest_roads = roads[nearest_roads_indices, ]
  # Calculate the distance to the nearest road using spatial indexes
  distances = sf::st_distance(segregated_points, nearest_roads, by_element = TRUE)
  # Add the distances to the 'rnet' object
  rnet$distance_to_road = round(as.numeric(distances), 1)

  return(rnet)
}
```
Benchmark results:

```r

library(microbenchmark)

benchmark_results = microbenchmark(
  old_function = osmactive::distance_to_road(cycle_network_old[100:1000,], driving_network_old),
  new_function = distance_to_road_new(cycle_network_old[100:1000,], driving_network_old),
  times = 10 
)
print(benchmark_results)

Unit: milliseconds
         expr       min        lq      mean   median         uq        max neval cld
 old_function 5707.7264 6471.3840 8228.5604 7929.338 10176.5201 10988.6668    10   b
 new_function  395.6285  416.6825  448.2298  420.526   514.5188   540.9303    10  a 
```

**Comment by Robinlovelace** [comment]
> I can make a PR. Benchmarking on the osm_edinburgh dataset shows the original function to be quicker, but this function seems much quicker on larger datasets

I was wondering why it was so slow and was wondering about a spatial index. Yes please to a PR!

**Comment by Robinlovelace** [comment]
Great to see the benchmark..

**Comment by Robinlovelace** [comment]
Results of my own tests on a smaller dataset below, the union had the opposite affect compared with the intended one!

```
system.time({
  cycle_net = distance_to_road(cycle_net, drive_net)
})
# 0.269s with union, 0.071s without
```

**Comment by Robinlovelace** [comment]
Only issue with that test: the command failed. Would be glad to hear your thoughts on this Hussein.
