### ISSUE TITLE
Segregation tag should be applied only to cycleway=track

### ISSUE THREAD

**Issue by mvl22** [nptscot/osmactive#61]
As noted at:
https://github.com/nptscot/osmactive/pull/60#discussion_r1800830631

the `segregated` tag, and its variants, should be scoped only to `cycleway=track` or `highway=cycleway` without `cycleway=...` designator. Any use on `cycleway=lane` is incorrect OSM data and should be ignored.

For a clear definition of this tag, see:
https://wiki.openstreetmap.org/wiki/Bicycle#Separation_from_other_road_users

Test cases:

This Way should end up as lane:
https://www.openstreetmap.org/way/1101640529

This Way should end up as cycle-track narrow (though really it is shared-use with a painted line, which shows the difficulty of getting sensible categories, in that most UK cycle tracks are really shared-use):
https://www.openstreetmap.org/way/975259772

**Comment by Robinlovelace** [comment]
I suggest not applying segregation rules for `highway=cycleway`, agree?

**Comment by Robinlovelace** [comment]
For the purposes of NPT classification, at least.

**Comment by mvl22** [comment]
> I suggest not applying segregation rules for highway=cycleway, agree?

No.

To be totally specific, `segregation` tagging applies to:

- `highway=cycleway` that does not also have `cycleway=lane`, i.e. a cycleway of some kind but not a lane on a road
- `cycleway=track`, i.e. highway of some kind includes a cycleway that is not a lane

**Comment by Robinlovelace** [comment]
Yes, but there's a difference between what is seggregated in reality and what the client wants. In this case the ask is for Goldenacre Path and similar paths to be classified as "Off-road" despite the fact it's shared use without seggregation.

**Comment by Robinlovelace** [comment]
But we can separate the logic in the npt classification function from the `cycleway_pedestrian_segregation()` logic.

**Comment by mvl22** [comment]
Yes, if you have a single category for all off-road, whether that be shared-use, shared-use with a line, narrow paths with a blue sign, or wide Dutch-standard infrastructure, then the segregation tag makes no difference for that category, as they'll all end up in the same bucket in the end.

**Comment by Robinlovelace** [comment]
> This Way should end up as lane:
> https://www.openstreetmap.org/way/1101640529

Disagree, this is bollard-separated light segregation, on OSM and in reality: https://www.openstreetmap.org/way/1101640529#map=19/53.814906/-1.562076

And: 
![image](https://github.com/user-attachments/assets/34d72137-1117-4f68-b2bb-f91ed0d1f83a)

Source: https://www.google.com/maps/@53.8147726,-1.5617113,3a,60y,320.21h,81.89t/data=!3m6!1e1!3m4!1spYVIvBBO2GgxecpnV163Zw!2e0!7i16384!8i8192?coh=205409&entry=ttu&g_ep=EgoyMDI0MTAxNC4wIKXMDSoASAFQAw%3D%3D

**Comment by Robinlovelace** [comment]
> This Way should end up as cycle-track narrow (though really it is shared-use with a painted line, which shows the difficulty of getting sensible categories, in that most UK cycle tracks are really shared-use):
> https://www.openstreetmap.org/way/975259772

What was it before? If you can be specific and provide screenshots/descriptions of what you saw that will help in future. Seems fixed in latest version (see released html for Leeds): 

![image](https://github.com/user-attachments/assets/dd6a7a3a-44fa-4e57-9381-aafbe369b227)

**Comment by mvl22** [comment]
> Disagree, this is bollard-separated light segregation

That is correct; the imagery I looked at was showing a lane only, but was presumably outdated.
