### ISSUE TITLE
Misclassification of the road type in OSM (Inverleith Place)

### ISSUE THREAD

**Issue by wangzhao0217** [nptscot/osmactive#64]
Inverleith Place is misclassified as residential in OpenStreetMap. However, according to Google Maps, this street is clearly identified as a B Road.

![image](https://github.com/user-attachments/assets/480387b9-150f-497b-919c-b7b717a017a9)

https://www.google.com/maps/@55.9659555,-3.2164077,3a,90y,250.66h,76.45t/data=!3m7!1e1!3m5!1sDDTXiVHumYtKqhHWVHY4mA!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D13.547915194962329%26panoid%3DDDTXiVHumYtKqhHWVHY4mA%26yaw%3D250.65814502891007!7i16384!8i8192?coh=205410&entry=ttu&g_ep=EgoyMDI0MTAyMS4xIKXMDSoASAFQAw%3D%3D

**Comment by Robinlovelace** [comment]
How is it classified in OS OpenRoads?

**Comment by Robinlovelace** [comment]
Consequences if it is misclassified (as I think it probably is):

- The traffic model, which uses highway type as a predictor (I think, right @juanfonsecaLS1 ?), will tend to under-estimate traffic volumes
- It will be seen as having a better level of service than it actually does have (classified as high LoS) as per below

![image](https://github.com/user-attachments/assets/27f5aebf-92b6-4d87-8044-f0a6e6e5350e)

Source: https://nptscot.github.io/#/clos/#15.01/55.96624/-3.21307

**Comment by Robinlovelace** [comment]
> according to Google Maps, this street is clearly identified as a B Road.

Based on the width of the road?

![image](https://github.com/user-attachments/assets/e269b5e2-5c3e-4b59-90af-c7d681122d21)

Source: https://www.google.com/maps/@55.9667292,-3.2150212,16.27z?entry=ttu&g_ep=EgoyMDI0MTAyMS4xIKXMDSoASAFQAw%3D%3D

The B901 road running perpendicular to the East is clearly marked as a B road so imagine it's the width that's the giveaway in the screenshot above, right?

**Comment by juanfonsecaLS1** [comment]
In the OS open roads is classified as a Minor Road. B roads and minor roads are very similar anyway. 
![image](https://github.com/user-attachments/assets/28d1cfb5-885a-435d-90f5-5d34a9012f06)
 The estimation model is not using the road class directly. However, the weights of the weighted network are based on the road class. I am changing the weights to be purely based on posted speed limit (30 mph for this road).

**Comment by Robinlovelace** [comment]
Thanks for the clarification Juan, sounds good to me. Do you have a view on this @mvl22 ? 

It is a misclassification based on this description from the [OSM Wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dresidential):

> The [highway](https://wiki.openstreetmap.org/wiki/Key:highway)=residential tag is used on roads that provide access to, or within, residential areas but which are not normally used as through routes.

**Comment by mvl22** [comment]
> B roads and minor roads are very similar anyway.

B roads are designed for through-traffic and tend to carry substantial traffic. I would not call them similar to minor roads. There are also C roads in the UK, between the two.

**Comment by mvl22** [comment]
Motorways, Trunk, A, B, C roads all have formal classifications in the UK.

If open roads doesn't call it a B road, it almost certainly isn't. The DfT [traffic counts data](https://bikedata.cyclestreets.net/trafficcounts/#12.72/55.96718/-3.19961) also don't feature it, but that covers A and B.

Functional classifications in OSM are defined here:
https://wiki.openstreetmap.org/wiki/Key:highway#Highway

and mapping of each country's road hierarchy onto these OSM tags is here:
https://wiki.openstreetmap.org/wiki/International_highway_classification_equivalence

> Inverleith Place is misclassified as residential in OpenStreetMap. However, according to Google Maps, this street is clearly identified as a B Road.

Is it? I can't actually see any indication from Google Maps that they are calling it that either. Can you clarify?

**Comment by mvl22** [comment]
> The B901 road running perpendicular to the East is clearly marked as a B road so imagine it's the width that's the giveaway in the screenshot above, right?

Google does not use the same rendering system as Mapnik/similar renders used by OSM.

Google are instead increasingly showing the actual real width of the road, even its specific shape, once you are zoomed in, rather than giving a standardised width based on classification. This can be confusing to people used to using traditional cartography.

**Comment by mvl22** [comment]
> I am changing the weights to be purely based on posted speed limit (30 mph for this road).

I hope you are treating 20 mph and 30 mph as the same in the case of non-classified streets: the shift from 30 -> 20 is fairly arbitrary in different places as the UK is essentially in a transition. Different local authorities are gradually deciding to make that change, e.g. Cambridge went 20 for local streets about 7 years ago. Currently, residential streets which look pretty identical will sometimes have 30, sometimes 20, depending on how progressive the local authority is.

**Comment by mvl22** [comment]
> The [[highway=residential](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dresidential)] tag is used on roads that provide access to, or within, residential areas but which are not normally used as through routes.

That description should be interpreted carefully. It definitely does not mean that a residential street that has become a rat-run should not be highway=residential.

The phrase 'not normally used as through routes' is out of date due to the growth of traffic in recent decades. I would properly phrase this more as 'not normally designed to be intended for use as a through route'.

The case of the UK, it really means not a classified type (motorway/trunk/A/B/C).

**Comment by Robinlovelace** [comment]
Relevant link: https://wiki.openstreetmap.org/wiki/Proposal:Highway:minor

Seems there is not currently an accepted highway=minor tag. That could mean that minor roads, that are not clearly residential or A/B roads or 'C' roads which I think have no national standing, with equivalent tags being primary, secondary, tertiary in OSM.

**Comment by Robinlovelace** [comment]
Closing for now as there's no clear action. Interesting discussion, thanks for opening it Zhao (my suggestion, in hindsight a discussion may have been a better place). It looks like it's not officially a B road, it is pretty wide and big, I'm not sure it's a residential road either. If actionable things come of this let's re-open or perhaps better open a new issue.

**Comment by mvl22** [comment]
> There is some level of subjectivity here: not sure it is possible to say definitively that this should or should not be tagged as residential on OSM

It's an unclassified road, so `highway=unclassified` or, if there are residences, `highway=residential`. So what is in OSM currently doesn't need changing.
