### ISSUE TITLE
Definition for off road cycleway

### ISSUE THREAD

**Issue by dabreegster** [nptscot/osmactive#67]
When highway=cycleway|path|footway|pedestrian is over 10 meters from the nearest driveable road, it gets classified as off-road cycleway.

https://www.openstreetmap.org/way/1137759929 shows up as this right now, but this looks like a narrow segregated / stepped track to me. https://www.openstreetmap.org/way/1209807768 is another case that doesn't seem like off-road.

My idea of off-road cycleway were things like https://www.openstreetmap.org/way/7973833 and https://www.openstreetmap.org/way/265320503 -- things with no parallel road nearby.

Before I mimic osmactive, are these intentionally defined this way, or is this an opportunity to tighten up the definition in both places?

**Comment by dabreegster** [comment]
https://github.com/nptscot/osmactive/blob/912b61e6d0b6403f1737989bb22a84ca5ea73af7/R/osmactive.R#L163
I'm not familiar with the ST definitions and have been reading docs, just wanted to check my interpretation. Is the process to look for all road linestrings near path linestrings, then find the _shortest_ distance between any two points on the linestrings?
![image](https://github.com/user-attachments/assets/532ce9f0-2045-442c-a8a8-78bb48654284)
In other words if the green path is usually far from the black road, but they get closest at the red point, that's the one we want to use for determining proximity?

I'm not sure here, because then paths at the edge of a park would fail:
![image](https://github.com/user-attachments/assets/8404276f-f219-4d1b-8562-cbcb23e3c5db)
This is clearly off-road, it just has a connection to the road.

Don't we want to do something like the line segment matching instead -- see if the cycleway is parallel-ish to and not very far from a road?

**Comment by dabreegster** [comment]
@mvl22 too

**Comment by mvl22** [comment]
> My idea of off-road cycleway were things like https://www.openstreetmap.org/way/7973833 and https://www.openstreetmap.org/way/265320503 -- things with no parallel road nearby.

That's what I would have thought too.

But tbh I don't know what the original intent by Robin's team was of having a distinct off-road category. To me what matters is the degree of segregation (i.e. safety) rather than proximity to a road. For utility cycling purposes, I don't think it makes any difference - people want the most direct route usually. Obviously for leisure purposes or people wanting a more pleasant route, absence of nearby traffic may well be welcomed, but it makes no difference to safety compared to a properly segregated cycleway alongside a road. So I think Robin really is the only person to answer this as he will know why this separate category was wanted.

**Comment by Robinlovelace** [comment]
> But tbh I don't know what the original intent by Robin's team was of having a distinct off-road category.

The intent, following guidance from the client, is to implement the CbD spec which states:

**Comment by Robinlovelace** [comment]
"Cycle tracks which are detached or entirely remote
from any associated road carriageway offer the
greatest level of protection from motor traffic and
therefore have the potential to be very attractive to
cycle users."

Source: https://www.transport.gov.scot/media/50323/cycling-by-design-update-2019-final-document-15-september-2021-1.pdf#page=71

**Comment by Robinlovelace** [comment]
> Don't we want to do something like the line segment matching instead

Yes, that would be better. Currently we're taking a more-or-less random point on the path and calculating its distance to roads. That's for computational issues, something that could be fixed by packaging `rnetmatch` / similar: https://github.com/nptscot/rnetmatch/issues/42

**Comment by Robinlovelace** [comment]
> When highway=cycleway|path|footway|pedestrian is over 10 meters from the nearest driveable road, it gets classified as off-road cycleway.
> 
> https://www.openstreetmap.org/way/1137759929 shows up as this right now

I see this on the latest version:

![image](https://github.com/user-attachments/assets/e33a2682-5bec-4316-a9fb-f4b5176299f1)

That's classified as "Segregated Track (wide)", right?

Source (will be able to include the layer in the URL after https://github.com/nptscot/nptscot.github.io/issues/266 is done): https://nptscot.github.io/#/clos/#15.65/55.955406/-3.1893

**Comment by Robinlovelace** [comment]
> https://www.openstreetmap.org/way/1209807768 is another case that doesn't seem like off-road.

Sections of that are indeed mis-classified:

![image](https://github.com/user-attachments/assets/2b8dabff-3b43-45d1-96ab-e936a6a8914f)

Quick fix: increase the distance threshold to more than 10m and add some alignment. I'm not sure if it's worth doing that now or waiting for https://github.com/nptscot/rnetmatch/issues/42 I don't sense this is urgent, although I agree, the classification is wrong here and likely in many other places.

Thoughts on increasing the threshold to 20 m?

**Comment by Robinlovelace** [comment]
Source: https://nptscot.github.io/#/clos/#17.4/55.959059/-3.183982

**Comment by Robinlovelace** [comment]
> Before I mimic osmactive, are these intentionally defined this way, or is this an opportunity to tighten up the definition in both places?

That's the key question, and sorry for slow response. Definitely opportunity to tighten-up the definition.

**Comment by mvl22** [comment]
> detached or entirely remote

Looks like the diagrams in the guidance do indeed not even reference any nearby road. So it's clear that 'detached' is intended to mean unrelated to road.

I would say the squiggly example you gave is essentially related to the road, even though it doesn't quite mirror its geometry.

**Comment by Robinlovelace** [comment]
> I would say the squiggly example you gave is essentially related to the road, even though it doesn't quite mirror its geometry.

Which example? Please be specific.

**Comment by Robinlovelace** [comment]
All 4 original examples are correct now I think:

![image](https://github.com/user-attachments/assets/ee8870c4-0560-46e0-967c-435af7228d15)


Source, newly added auto-updating documentation: https://nptscot.github.io/osmactive/articles/classify-cbd.html

(Will be updated in a few minutes thanks to GitHub Actions.)


Would be great to have more feedback on any other mis-classified ways, let us know if you spot any @dabreegster, @mvl22 and anyone else interested. To test any other segments, see here and try adding additional ways by editing this bit of code:

**Comment by Robinlovelace** [comment]
https://github.com/nptscot/osmactive/blob/a02b8a986378fb929778d75e5bbe4c38c853b996/vignettes/classify-cbd.Rmd#L61-L69

**Comment by Robinlovelace** [comment]
> > Which example? Please be specific.
> 
> Of the two green lines in the posting at the start of the thread, the one that is more squiggly - the first one.

All fixed now, right? If there are any more incorrectly classified ways please post here, with reference to links to OSM and either a screenshot from https://nptscot.github.io/osmactive/articles/classify-cbd.html (more up-to-date) or the dev version of the NPT.

**Comment by dabreegster** [comment]
Thanks for the clarifications and fixes here! For mimicking this in NPW, I still need to figure out:

> Yes, that would be better. Currently we're taking a more-or-less random point on the path and calculating its distance to roads. That's for computational issues, something that could be fixed by packaging rnetmatch / similar

But I'll work on that on my end. If a linestring matching winds up being more appropriate, I'll make sure results match here.
